config/routes.rb
Rails.application.routes.draw do

  get 'users/sign_in'   => 'root#login'
  get 'users/sign_out'  => 'root#logout'
  devise_for :users
  root to: "contacts#index"

  resources :contacts
  resources :events
  
  resources :orders do
    collection do
      get :add_customer
    end
  end

  resources :shopping do
    collection do
      get :start
      post :start
    end
  end

  get '/subregion_options' => 'country#subregion_select'

  # constraints: OnlyAjaxRequest.new,
  api_version module: 'Api', path: { value: 'api' }, default: true do
    resources :contacts
    resources :comments
  end
end

app/controllers/shopping_controller.rb
class ShoppingController < ApplicationController

  def start
    if request.post?
      # if user clicks 'Start shopping' button, go to personal order cart page
      if params[:order_type] == "personal"
        cookies.delete(:bf_shop_ctx)
        cookies[:bf_shop_ctx] = {
          domain: 'barefootbooks.com', # TODO don't hardcode this
          expires: 1.day.ago
        }

        redirect_to magento_url('checkout/cart')
      else
        @event = Event.find(params[:event_id]) if params[:event_id]
        shopping_context = {}
        shopping_context[:address] = params[:address] unless params[:address].blank?
        if @event && params[:order_type] != 'non-event'
          shopping_context[:id] = @event.id
          shopping_context[:event_code] = @event.affiliate_code
          shopping_context[:event_name] = @event.name
        end
        shopping_context[:order_type] = params[:order_type]
        cookies[:bf_shop_ctx] = {
          domain: 'barefootbooks.com', # TODO don't hardcode this
          value: shopping_context.to_json,
          expires: 1.day.from_now
        }

        redirect_to add_customer_orders_path(event_id: @event.id)
      end
    end
  end
end

app/views/shopping/start.html.slim
.title
  h1 Start shopping
.row
  = form_tag start_shopping_index_path do
    input#order_type type="hidden" name='order_type'
    .col-sm-6
      h2 Place a personal order
      h3 Sales aims, samples or cash & carry. Ships to one address only.
      button.btn.btn-primary onclick='$(this.form).find("#order_type").attr("value", "personal"); this.form.submit(); return false;' Start shopping

      h4 Your active promotions
      p.text-gray-darker Free shopping on orders $100
    .col-sm-4
      h2 Order for an event
      h3 Select an Event and Order
      .form-group
        = select_tag :event_id, options_from_collection_for_select(Event.all, "id", "name"), { class: "form-control" } 
      .form-group
        button.btn.btn-default.text-primary onclick='$(this.form).find("#order_type").attr("value", "customer"); this.form.submit(); return false;' Customer Order &#9654;
        button.btn.btn-default.text-primary onclick='$(this.form).find("#order_type").attr("value", "host"); this.form.submit(); return false;' Host Order &#9654;
      .text-center
        span or &nbsp;
        button.btn.btn-default.text-warning onclick='$(this.form).find("#order_type").attr("value", "non-event"); this.form.submit(); return false;' Place Non-event Order