config/routes.rb
Rails.application.routes.draw do

  get 'users/sign_in'   => 'root#login'
  get 'users/sign_out'  => 'root#logout'
  devise_for :users
  root to: "contacts#index"

  resources :contacts
  resources :events
  
  resources :orders do
    collection do
      get :add_customer
    end
  end

  resources :shopping do
    collection do
      get :start
      post :start
    end
  end

  get '/subregion_options' => 'country#subregion_select'

  # constraints: OnlyAjaxRequest.new,
  api_version module: 'Api', path: { value: 'api' }, default: true do
    resources :contacts
    resources :comments
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  acts_as_commentable
  
  belongs_to :event_type
  belongs_to :host, foreign_key: 'host_id', class_name: 'Contact'

  before_create :generate_affiliate_code

  scope :active, -> { where("STR_TO_DATE(CONCAT(end_date, ' ', end_time), '%Y-%m-%d %H:%i') > ?", Time.now) }
  scope :past, -> { where("STR_TO_DATE(CONCAT(end_date, ' ', end_time), '%Y-%m-%d %H:%i') < ?", Time.now) }
  
  def full_address
    country = Carmen::Country.coded(self.country)
    if country.nil?
      country = self.country
    else
      if country.subregions?
        state = country.subregions.coded(self.state).try(:name)
      end
      country = country.name
    end

    state ||= self.state
    "#{self.city}, #{state}, #{country}"
  end

  def as_json(options = {})
    return {
      id:         id.to_s,
      name:       name,
      eventType:  event_type,
      host:       host,
      affiliateCode: affiliate_code,
      updatedAt:  updated_at.to_i,
      createdAt:  created_at.to_i
    }
  end

  protected

  def generate_affiliate_code
    self.affiliate_code = loop do
      code = Faker::Code.isbn
      break code unless Event.exists?(affiliate_code: code)
    end
  end
end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  has_many :events

  def as_json(options = {})
    return {
      id:         id.to_s,
      name:       name,
      updatedAt:  updated_at.to_i,
      createdAt:  created_at.to_i
    }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_resource, only: [:show, :edit, :update, :destroy]

  def index
    if params[:status] == "active"
      @events = Event.active.page(params[:page]).per(10)
    elsif params[:status] == "past"
      @events = Event.past.page(params[:page]).per(10)
    else
      @events = Event.page(params[:page]).per(10)
    end
  end

  def show
    respond_to do |format|
      if params[:callback]
        format.js { render json: @event, callback: params[:callback] }
      else
        format.json { render json: @event }
      end
    end
  end

  def new
    @event = Event.new
    @event.country = 'US'
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: "Event has been created successfully"
    else
      redirect_to :back, alert: "Unable to create event"
    end
  end

  def update
    if @event.update_attributes(event_params)
      redirect_to events_path, notice: "Event has been updated successfully"
    else
      redirect_to :back, alert: "Unable to update event"
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: "Event has been deleted successfully."
  end

  private

  def event_params
    params.require(:event).permit!
  end

  def find_resource
    @event = Event.find(params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_add_contact_modal.html.slim
#create-contact.modal.fade aria-hidden="true" aria-labelledby="contactLabel" role="dialog" tabindex="-1" 
  .modal-dialog
    = simple_form_for :contact, url: contacts_path, remote: true,
                      defaults: { wrapper_html: { class: "col-sm-6" }, input_html: { class: "form-control" }}, 
                      html: { id: "new_contact", method: :post } do |f|
      .modal-content
        .modal-header
          button.close data-dismiss="modal" type="button" 
            span aria-hidden="true"  &times;
            span.sr-only Close
          h4#contactLabel.modal-title Create Contact
        .modal-body
          .alert.alert-danger.hide
            button.close data-dismiss="alert" aria-hidden="true" type="button" &times;
            .content
          = render "contacts/form", f: f
        .modal-footer
          button.btn.btn-default data-dismiss="modal" type="button"  Close
          button.btn.btn-default Customer Order &#9654;
          button.btn.btn-default Horst Order &#9654;

app/views/events/_form.html.slim
h2 Event Details
.row
  = f.input :event_type_id, collection: EventType.all, required: true, label: "Event Type", selected: 1
  = f.input :name, required: true, label: "Event Name", input_html: { placeholder: "e.g., Sue's family party; Preschool fundraiser"}
label.control-label
  = f.check_box :is_public
  | This is a public event (it will be displayed on your market place).

h2 Host Information
div ng-init="hosting_type='customer'"
  label.control-label
    = f.radio_button :hosting_type, "customer", "ng-model"=>"hosting_type"
    | A customer is hosting this event
.form-group
  label.control-label
    = f.radio_button :hosting_type, "myself", "ng-model"=>"hosting_type"
    | I am hosting this event
label ng-if="hosting_type == 'myself'" Host Name
.row ng-if="hosting_type == 'myself'"
  .col-sm-6
    = f.collection_select :host_id, Contact.all, :id, :full_name, {}, { class: "form-control" }
  .pull-left
    span or &nbsp;
    a.btn.btn-default data-toggle="modal" data-target="#create-contact" Add New Contact
h2 Location
div ng-init="location_type='customer'"
  label.control-label
    = f.radio_button :location_type, "customer", "ng-model"=>"location_type"
    | Same as Host Address
.form-group
  label.control-label
    = f.radio_button :location_type, "", "ng-model"=>"location_type"
    | Specify New Location
.row ng-if="location_type!='customer'"
  = f.input :address1
  = f.input :address2
  = f.input :country, collection: wishlist_countries, label_method: :name, value_method: :code, selected: 'US', input_html: { class: 'country-select form-control'}
  .col-sm-6.control-group
    = f.label :state
    = render partial: 'shared/subregion_select', locals: { object: :contact, parent_region: f.object.country }
  = f.input :city
  = f.input :zipcode

h2 Date and Time
.row
  .col-sm-4
    = f.label :start_date
    = f.text_field :start_date, class: "dateonly form-control"
  .col-sm-3
    = f.label :start_time
    = f.text_field :start_time, class: "timepicker form-control"
.row.form-group
  .col-sm-4
    = f.label :end_date
    = f.text_field :end_date, class: "dateonly form-control"
  .col-sm-3
    = f.label :end_time
    = f.text_field :end_time, class: "timepicker form-control"

app/views/events/edit.html.slim
.row
  .col-sm-9
    h1 Edit an Event
    = simple_form_for @event, 
                      defaults: { wrapper_html: { class: "col-sm-6" }, input_html: { class: "form-control" }}, 
                      input_html: { class: "form-horizontal" } do |f|
      = render "form", f: f

      = link_to "Cancel", events_path, class: "btn btn-default"
      = f.submit "Edit event", class: "btn btn-primary"
= render "add_contact_modal"

app/views/events/index.html.slim
h1 My Events

.row
  .col-sm-9
    h2 All Events
    .row
      .col-sm-2
        label.control-label
          input type="checkbox" ng-model="select_all" style="margin-top: 10px;"
          | Select All
    .text-right= page_entries_info @events
    .table-responsive
      table.table.table-striped
        tbody
          tr
            td
            td Event Name
            td Type
            td Date & Time
            td Affiliate Code

          - @events.each do |event|
            tr
              td
                input type="checkbox" ng-checked="select_all == true"
              td= link_to event.name, event
              td= event.event_type.try(:name)
              td
                p Start: #{event.start_date}, #{event.start_time}
                p End: #{event.end_date}, #{event.end_time}
              td
                a= event.affiliate_code
    .text-right= page_entries_info @events
    .pull-right
      = paginate @events

  .col-sm-3.search-panel
    .form-group
      = link_to "Create new event &#9654;".html_safe, new_event_path, class: "btn btn-primary btn-streched"
    .well
      br
      / h2 Quick Search
      / p
      /   a
      /     b.text-gray-darker View All
      /     span.small &raquo;
      / p
      /   a.text-gray href="/events?status=active" Active Events
      / p
      /   a.text-gray href="/events?status=past" Past Events
      h4 Event Details
      .form-group
        b Event Name
        p Jane Dos world animal's party
      .form-group
        b Type
        p 
      .form-group
        b Host
        p Jane Dos world animal's party
      .form-group
        b Date and Time
        p Jane Dos world animal's party
      .form-group
        b Orders accepted until:
        p 
      .form-group
        b Tracking Code
        p 


      hr
      h4 Activity 
      p Orders: 0
      p Qualifying Volumn: $0.00
      p Bonus Volumn: $0.00

      hr
      h4 Host Earnings
      b Earned this event
      p Free Gift Credit: $0.00
      p Qualified Host Gifts: 0

app/views/events/new.html.slim
.row
  .col-sm-9
    h1 Create an Event
    = simple_form_for @event, 
                      defaults: { wrapper_html: { class: "col-sm-6" }, input_html: { class: "form-control" }}, 
                      input_html: { class: "form-horizontal" } do |f|
      = render "form", f: f

      = link_to "Cancel", events_path, class: "btn btn-default"
      = f.submit "Create Event", class: "btn btn-primary"
= render "add_contact_modal"

app/views/events/show.html.slim
.show-page
  = link_to "<< Back to my Events", events_path, class: "small"

  .row
    .col-sm-9
      .title
        h1 = @event.name
        .row
          .col-sm-4
            b Type: 
            span= @event.event_type.try(:name)
          .col-sm-4
            b Affiliate Code
            span= @event.affiliate_code
          .pull-right
            = link_to "Edit event", edit_event_path(@event), class: "btn btn-sm btn-primary"
            = link_to "Delete event", event_path(@event), class: "btn btn-sm btn-default", confirm: "Are you sure?", data: { method: :delete }
      .row
        .col-sm-8
          h2 Host Information
          .form-group
            b Host Name
            p
              a= @event.host.full_name
          .form-group
            b Email Address
            p= @event.host.email
          .form-group
            b Mobile phone
            p= @event.host.mobile_phone
          .form-group
            b Event Location
            p= @event.full_address
          h2 Date and Time
          .form-group
            p
              b Start :
              span #{@event.start_date}, #{@event.start_time}
            p
              b End :
              span #{@event.end_date}, #{@event.end_time}
        .col-sm-4
          br
          = image_tag "missing.jpg"
      hr

      #comments ng-controller="CommentCtrl" ng-init="getComments('Event', #{@event.id})"
        .row
          .col-sm-6
            .form-group
              label Notes
              textarea.form-control rows=3 name="note" ng-model="comment"
            a.btn.btn-primary ng-click="createComment('Event', #{@event.id})" Add note
          .col-sm-6
            h2 Available Credits
            p Free Gift Credit(FGC): $20.00
            p Qualified Host Gifts(60% off current host special): 3

        h2 Previous Notes
        div ng-repeat="comment in comments"
          .row
            .col-xs-9.col-sm-10
              p ng-bind="comment.comment"
              span.text-gray ng-bind="comment.created_at | date : 'd MMMM y'"
            .col-xs-3.col-sm-2.text-right
              a ng-click="deleteComment(comment)" remove
          hr