config/routes.rb
Rails.application.routes.draw do

  get 'users/sign_in'   => 'root#login'
  get 'users/sign_out'  => 'root#logout'
  devise_for :users
  root to: "contacts#index"

  resources :contacts
  resources :events
  
  resources :orders do
    collection do
      get :add_customer
    end
  end

  resources :shopping do
    collection do
      get :start
      post :start
    end
  end

  get '/subregion_options' => 'country#subregion_select'

  # constraints: OnlyAjaxRequest.new,
  api_version module: 'Api', path: { value: 'api' }, default: true do
    resources :contacts
    resources :comments
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  acts_as_commentable
  
  has_many :events, foreign_key: 'host_id'
  has_many :children, dependent: :destroy

  validates_presence_of :first_name, :last_name
  validates_uniqueness_of :email, allow_blank: true
  
  # Scope methods
  scope :by_first_name, -> first_name { where("first_name like ?", "%#{first_name}%") }
  scope :by_last_name, -> last_name { where("last_name like ?", "%#{last_name}%") }
  scope :by_email, -> email { where(first_name: email) }
  scope :by_company, -> company { where(company: company) }
  scope :by_country, -> country { where(country: country) }
  scope :by_state, -> state { where(state: state) }
  scope :by_city, -> city { where(city: city) }
  # scope :active, -> where { where(active: true) }

  GENDER = %w[Boy Girl]
  RELATIONSHIP = %w[Son/Daughter Grandson/Granddaughter Niece/Nephew Other]
  
  def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |contact|
        csv << contact.attributes.values_at(*column_names)
      end
    end
  end

  def full_address
    country = Carmen::Country.coded(self.country)
    if country.nil?
      country = self.country
    else
      if country.subregions?
        state = country.subregions.coded(self.state).try(:name)
      end
      country = country.name
    end

    state ||= self.state
    "#{self.city}, #{state}, #{country}"
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def as_json(options = {})
    return {
      id:         id.to_s,
      name:       full_name,
      firstName:  first_name,
      lastName:   last_name,
      city:       city,
      state:      state,
      country:    country,
      updatedAt:  updated_at.to_i,
      createdAt:  created_at.to_i
    }
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  before_action :authenticate_user!
  before_action :find_resource, only: [:show, :edit, :update, :destroy]
  include ContactScopes

  def index
    @contacts = apply_scopes(Contact).page(params[:page]).per(10).order(id: :desc)
    respond_to do |format|
      format.html
      format.csv { send_data @contacts.to_csv }
    end
  end

  def new
    @contact = Contact.new
    @contact.country = 'US'
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      @contact.comments.create({comment: params[:note]}) if params[:note].present?
      add_children
      respond_to do |format|
        format.json { render json: @contact, status: :created }
        redirect_url = params[:contact][:event_id].present? ? magento_url('checkout/cart') : contact_path(@contact)
        format.html { redirect_to redirect_url, notice: "Event has been created successfully" }
      end
    else
      respond_to do |format|
        format.json { render json: @contact.errors.full_messages, status: :unprocessable_entity }
        redirect_url = params[:contact][:event_id].present? ? "orders/add_customer" : :new
        @event = Event.find(params[:contact][:event_id]) if params[:contact][:event_id].present?
        format.html { render redirect_url }
      end
    end
  end

  def update
    if @contact.update_attributes(contact_params)
      redirect_to contacts_path, notice: "Contact has been updated successfully"
    else
      render :edit
    end
  end

  def destroy
    @contact.destroy
    redirect_to contacts_path, notice: "Contact has been deleted successfully."
  end

  private

  def add_children
    return if @contact.nil? or params[:children].nil?

    @contact.children.destroy_all
    params[:children].each do |child|
      next if child["name"].blank?
      @contact.children.create(child_params(child))
    end
  end

  def contact_params
    params.require(:contact)
          .permit(:first_name, :last_name, :email, :company, :address1, :address2, :country, :state,
                  :city, :zipcode, :mobile_phone, :alternate_phone, :interested_buying,
                  :interested_hosting, :interested_joining)
  end

  def child_params(child_param)
    child_param.permit(:name, :birthday, :gender, :relationship)
  end

  def find_resource
    @contact = Contact.find(params[:id])
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def wishlist_countries
    Carmen::Country.all.select{|c| %w{US CA GB AT BE DK FR DE GG IE IM IT JE LU NL ES SE CH}.include?(c.code)}
  end

  def csv_contacts_path
    if request.fullpath == "/"
      "/contacts.csv"
    elsif request.fullpath.include?("/?")
      request.fullpath.gsub!("\/?", "contacts.csv?")
    else
      request.fullpath.gsub!("contacts", "contacts.csv")
    end
  end
end

app/views/contacts/_form.html.slim
h2 Account Details
= f.error_notification
.row
  = f.input :first_name, required: true
  = f.input :last_name, required: true
  = f.input :email
  = f.input :company
h2 Contact Info
.row
  = f.input :address1
  = f.input :address2
  = f.input :country, collection: wishlist_countries, label_method: :name, value_method: :code, selected: 'US', input_html: { class: 'country-select form-control'}
  .col-sm-6.control-group
    = f.label :state
    = render partial: 'shared/subregion_select', locals: { object: :contact, parent_region: f.object.try(:country) }
  = f.input :city
  = f.input :zipcode
  = f.input :mobile_phone
  = f.input :alternate_phone
#children
  h2 Children
  p Send birthday wishes and/or custom book and gift suggestions for the children in your contact life
  - if @contact.nil? || @contact.children.empty?
    .row
      .col-sm-4
        = label_tag :name, "Child's Name"
        input.form-control name="children[][name]"
      .col-sm-3
        = label_tag :birthday, "Child's Birthday"
        input.dateonly.form-control name="children[][birthday]"
      .col-sm-2
        = label_tag :gender
        = select_tag "children[][gender]", options_for_select(Contact::GENDER), class: 'form-control'
      .col-sm-3
        = label_tag :relationship
        = select_tag "children[][relationship]", options_for_select(Contact::RELATIONSHIP), class: 'form-control'
  - else
    - @contact.children.each do |child|
      .row
        .col-sm-4
          = label_tag :name, "Child's Name"
          input.form-control name="children[][name]" value="#{child.name}"
        .col-sm-3
          = label_tag :birthday, "Child's Birthday"
          input.dateonly.form-control name="children[][birthday]" value="#{child.birthday.to_date}"
        .col-sm-2
          = label_tag :gender
          = select_tag "children[][gender]", options_for_select(Contact::GENDER, child.gender), class: 'form-control'
        .col-sm-3
          = label_tag :relationship
          = select_tag "children[][relationship]", options_for_select(Contact::RELATIONSHIP, child.relationship), class: 'form-control'

a#add-child.small Add another child >>
#child-template.row.hide
  .col-sm-4
    = label_tag :name, "Child's Name"
    input.form-control name="children[][name]"
  .col-sm-3
    = label_tag :birthday, "Child's Birthday"
    input.dateonly.form-control name="children[][birthday]"
  .col-sm-2
    = label_tag :gender
    = select_tag "children[][gender]", options_for_select(Contact::GENDER), class: 'form-control'
  .col-sm-3
    = label_tag :relationship
    = select_tag "children[][relationship]", options_for_select(Contact::RELATIONSHIP), class: 'form-control'

.row.form-group
  .col-sm-6
    h2 Interested in
    .form-group
      label.control-label
        = f.check_box :interested_buying
        | Buying Barefoot Books & Gifts
      label.control-label
        = f.check_box :interested_hosting
        | Hosting a barefoot event
      label.control-label
        = f.check_box :interested_joining
        span Joining as an Ambassador to start a business
    .form-group
      label Notes
      textarea.form-control rows=3 name="note"

  .col-sm-6
    h2 Email Sign-up
    label
      input type="checkbox" checked="checked"
      | This customer wishes to recieve emails from the Barefoot Books home office

app/views/contacts/_right_panel.html.slim
.form-group
  = link_to "Create new contact &#9654;".html_safe, new_contact_path, class: "btn btn-primary btn-streched"
.well
  h2 Search Contacts

  = form_tag contacts_path, method: :get do
    .form-group
      = label_tag :first_name, "First Name"
      = text_field_tag :first_name, params[:first_name], class: "form-control"

    .form-group
      = label_tag :last_name, "Last Name"
      = text_field_tag :last_name, params[:last_name], class: "form-control"

    .form-group
      = label_tag :company, "Company Name"
      = text_field_tag :company, params[:company], class: "form-control"

    .form-group
      = label_tag :member_type
      = text_field_tag :member_type, params[:member_type], class: "form-control"

    .form-group
      = label_tag :country
      = select_tag :country, options_from_collection_for_select(wishlist_countries, "code", "name", params[:country]), { prompt: "Select Country", class: "form-control country-select" } 

    .form-group
      = label_tag :state, "State/Country/Province"
      = render partial: 'shared/subregion_select', locals: { parent_region: params[:country] }
    
    .form-group
      = label_tag :city, "City/Town"
      = text_field_tag :city, params[:city], class: "form-control"

    .form-group
      button.btn.btn-primary.btn-sm Search Contacts

  h2 Quick Search
  p
    = link_to contacts_path, class: "text-default" do
      b.text-gray View All
      span.small &raquo;
  p.text-gray Past Customers
  p.text-gray Past Hosts

  hr.gray-border.border-solid
  p.text-gray Potential Ambassadors
  p.text-gray Potential Hosts
  p.text-gray Leads from Home Office
  p.text-gray Referral Orders

  hr.gray-border.border-solid
  p.text-gray Has Store Credit

app/views/contacts/edit.html.slim
.row
  .col-sm-9
    h1 Edit Contact
    = simple_form_for @contact, 
                      defaults: { wrapper_html: { class: "col-sm-6" }, input_html: { class: "form-control" }}, 
                      input_html: { class: "form-horizontal" } do |f|
      = render "form", f: f

      = link_to "Cancel", contacts_path, class: "btn btn-default"
      = f.submit "Edit Contact", class: "btn btn-primary"

app/views/contacts/index.csv.slim
table
  tbody
    tr
      td
      td First Name
      td Last Name
      td Type
      td Contact Info

    - @contacts.each do |contact|
      tr
        td
          input type="checkbox" ng-checked="select_all == true"
        td= link_to contact.first_name, contact
        td= link_to contact.last_name, contact
        td Contact
        td
          p= contact.company
          p= contact.mobile_phone.nil? ? contact.alternate_phone : contact.mobile_phone
          p.copy
            a
              small= contact.email
          p= contact.full_address

app/views/contacts/index.html.slim
h1 My Contacts

.row
  .col-sm-9
    h2 All Contacts
    .row.form-group
      .col-sm-2
        label.control-label
          input type="checkbox" ng-model="select_all" style="margin-top: 10px;"
          | Select All
      .col-sm-9
        a.btn.btn-default href="mailto:#{@contacts.map(&:email).join(',')}" Send email
        = link_to "Export contacts", csv_contacts_path, class: "btn btn-default"
    .text-right= page_entries_info @contacts
    .table-responsive
      table.table.table-striped
        tbody
          tr
            td
            td First Name
            td Last Name
            td Type
            td Contact Info

          - @contacts.each do |contact|
            tr
              td
                input type="checkbox" ng-checked="select_all == true"
              td= link_to contact.first_name, contact
              td= link_to contact.last_name, contact
              td Contact
              td
                p= contact.company
                p= contact.mobile_phone.nil? ? contact.alternate_phone : contact.mobile_phone
                p.copy
                  a
                    small= contact.email
                p= contact.full_address
    .text-right= page_entries_info @contacts
    .pull-right
      = paginate @contacts

  .col-sm-3.search-panel.hidden-xs
    = render 'right_panel'

app/views/contacts/new.html.slim
.row
  .col-sm-9
    h1 Create New Contact
    = simple_form_for @contact, defaults: { wrapper_html: { class: "col-sm-6" }, input_html: { class: "form-control" }}, input_html: { class: "form-horizontal" } do |f|
      = render "form", f: f

      = link_to "Cancel", contacts_path, class: "btn btn-default"
      = f.submit "Create Contact", class: "btn btn-primary"

app/views/contacts/show.html.slim
.show-page
  = link_to "<< Back to my contacts", contacts_path, class: "small"

  .row
    .col-sm-9
      .title
        h1 = @contact.full_name
        .row
          .col-sm-2
            b Type: 
            span Host
          .col-sm-4
            b Source: 
            span Ambassador Contact
          .pull-right
            = link_to "Edit Contact", edit_contact_path(@contact), class: "btn btn-sm btn-primary"
            = link_to "Delete Contact", contact_path(@contact), class: "btn btn-sm btn-default", confirm: "Are you sure?", data: { method: :delete }
      .row
        .col-sm-6
          h2 Contact Info
          .form-group
            b Email Address
            p
              a= @contact.email
          .form-group
            b Mobile Phone
            p= @contact.mobile_phone
          .form-group
            b Mailing Address
            p= @contact.full_address

        .col-sm-6
          h2 Children
          - child = @contact.children.first
          p
            b Name: 
            = child.try(:full_name)
          p
            b Birthday: 
            = child.try(:full_name)
          p
            b Gender: 
            = child.try(:gender)
          p
            b Relationship: 
            = child.try(:relationship)

          h2 Interested in...
          - if @contact.interested_buying
            p
              i.glyphicon.glyphicon-ok.text-warning
              span  Buying Barefoot Books & Gifts
          - if @contact.interested_hosting
            p
              i.glyphicon.glyphicon-ok.text-warning
              span  Hosting a barefoot event
          - if @contact.interested_joining
            p.form-group
              i.glyphicon.glyphicon-ok.text-warning
              span  Joining as a Ambassador to start a business

          p
            b Email Sign-up 
          i.glyphicon.glyphicon-ok.text-warning
          span  Opted in to recieve email from home office
      hr
      #comments ng-controller="CommentCtrl" ng-init="getComments('Contact', #{@contact.id})"
        .row
          .col-sm-6
            .form-group
              label Notes
              textarea.form-control rows=3 name="note" ng-model="comment"
            a.btn.btn-primary ng-click="createComment('Contact', #{@contact.id})" Add note
          .col-sm-6
            h2 Available Credits
            p Free Gift Credit(FGC): $20.00
            p Qualified Host Gifts(60% off current host special): 3

        h2 Previous Notes
        div ng-repeat="comment in comments"
          .row
            .col-xs-9.col-sm-10
              p ng-bind="comment.comment"
              span.text-gray ng-bind="comment.created_at | date : 'd MMMM y'"
            .col-xs-3.col-sm-2.text-right
              a ng-click="deleteComment(comment)" remove
          hr