config/routes.rb
Rails.application.routes.draw do

  get 'users/sign_in'   => 'root#login'
  get 'users/sign_out'  => 'root#logout'
  devise_for :users
  root to: "contacts#index"

  resources :contacts
  resources :events
  
  resources :orders do
    collection do
      get :add_customer
    end
  end

  resources :shopping do
    collection do
      get :start
      post :start
    end
  end

  get '/subregion_options' => 'country#subregion_select'

  # constraints: OnlyAjaxRequest.new,
  api_version module: 'Api', path: { value: 'api' }, default: true do
    resources :contacts
    resources :comments
  end
end

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar
  = render "layouts/top"
  #menu-bar.container
    .row
      .navbar-header
        = link_to root_path, class: 'navbar-brand hidden-xs'
          = image_tag 'logo.png'

        button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
    .row
      .teal-leftcap.pull-left
      .teal-bar.pull-left
      .teal-rightcap.pull-left

    .row
      .collapse.navbar-collapse
        ul.nav.navbar-nav
          = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
li= link_to 'HOME', contacts_path, class: active_class('contacts')
li= link_to 'PARTIES & EVENTS', events_path, class: active_class('events')
li= link_to 'ORDER & SHOP', '/shopping/start', class: active_class('')
li= link_to 'MARKETING', contacts_path, class: active_class('')
li= link_to 'TRAINING & MEETINGS', contacts_path, class: active_class('')
li= link_to 'REPORTS', contacts_path, class: active_class('')

app/views/layouts/_top.html.slim
.top.navbar-fixed-top
  .container
    h3.pull-left.hidden-xs
      a www.barefootbooks.com
    
    #search.pull-right
      form#search_mini_form.navbar-form action="http://store.barefootbooks.com/catalogsearch/result/" method="get" 
        input name="order" type="hidden" value="relevance" 
        input name="dir" type="hidden" value="desc" 
        input#search.input-text.input-sm name="q" placeholder=("Search Products...") type="text" value="" 
        button.btn.btn-sm type="submit" 
          i.glyphicon.glyphicon-search
    ul.list-inline.pull-right
      - if user_signed_in?
        li
          a
            | Hi, #{current_user.name}!
          - if current_user.avatar
            span.avatar
              = image_tag current_user.avatar

        li
          = link_to "Basket", magento_url("checkout/cart")
        li
          = link_to('Sign out', destroy_user_session_path, :method => :delete)
      - else
        li
          = link_to('Sign in!', barefoot_sign_in_url)
      li.dropdown
        a.dropdown-toggle data-toggle="dropdown" href="#" 
          | You are in North America
          span.caret
        ul.dropdown-menu role="menu" 
          li
            a href="#"  North America
          li
            a href="#"  Europe

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Barefoot'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Barefoot'}"
    = stylesheet_link_tag "application", :media => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  body ng-app="barefootApp"
    header
      = render 'layouts/navigation'
    main[role="main"]
      = render 'layouts/messages'
      = yield